server:
  port: 8080
  servlet:
    context-path: "/ra"
spring:
  application:
    name: "repo-activo"
  devtools:
    add-properties: false
  # Configuración H2
  #  h2:
  #    console:
  #      enabled: true
  #      path: "/h2"
  profiles:
    active: "local"
    include: null
  sql:
    init:
      mode: always
      platform: postgresql
  datasource:
    # Configuración PostgreSQL
    url: "jdbc:postgresql://localhost:5432/repo_activo_jsonb"
    username: "postgres"
    password: "1111"
    driverClassName: "org.postgresql.Driver"
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  # Configuración H2
  #    url: "jdbc:h2:mem:test"
  #    username: "sa"
  #    password: ""
  #    driverClassName: "org.h2.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

aws:
  db:
    region: "MedellinCity"
    secretName: "CualquierCosa"
    start-url: "cualquierCosaIgualNoSeUsa"
